version: '3'

vars:
  BINARY: vibe
  MODULE: github.com/valiro-ai/vibe

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the CLI binary
    cmds:
      - go build -o {{.BINARY}} .
    sources:
      - "**/*.go"
    generates:
      - "{{.BINARY}}"

  run:
    desc: Run the CLI (pass args after --)
    cmds:
      - go run . {{.CLI_ARGS}}

  install:
    desc: Install the CLI to $GOPATH/bin
    cmds:
      - go install .

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY}}

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy go.mod dependencies
    cmds:
      - go mod tidy

  test:
    desc: Run tests
    cmds:
      - go test ./...

  check:
    desc: Run all checks (fmt, vet, test)
    cmds:
      - task: fmt
      - task: vet
      - task: test

  dev:
    desc: Build and run sep status
    cmds:
      - task: build
      - ./{{.BINARY}} sep status

  init-workflow:
    desc: Initialize vibe workflow in current directory
    cmds:
      - task: build
      - ./{{.BINARY}} init
